Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Models/DataAccess/grade.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int gradeid { get; set; }
        public string classname { get; set; }
        public string sectionname { get; set; }
        public string subjectname { get; set; }
        public string studentname { get; set; }
        public int quiz1 { get; set; }
        public int quiz2 { get; set; }
        public int assignment1 { get; set; }
        public int halfyearlygrade { get; set; }
        public int quiz3 { get; set; }
        public int quiz4 { get; set; }
        public int assignment2 { get; set; }
        public int finalexamgrade { get; set; }
    }
}

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Models/DataAccess/teacher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int id { get; set; }
        public string teacherid { get; set; }
        public string teachername { get; set; }
        public string teacherpassword { get; set; }
        public string teacherbloodgroup { get; set; }
        public string teacheremail { get; set; }
        public Nullable<int> subjectid { get; set; }
        public int teacherphone { get; set; }
        public int teachersalary { get; set; }
    }
}

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Models/Extended/grade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    [MetadataType(typeof(gradedata))]
    public partial class grade
    {
    }

    public class gradedata
    {
        [Display(Name = "Grade Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Grade Id is required")]
        public int gradeid { get; set; }

        [Display(Name = "Student Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Student Name is required")]
        public string studentname { get; set; }

        [Display(Name = "Class Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Class Name is required")]
        public string classname { get; set; }

        [Display(Name = "Section Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Section Name is required")]
        public string sectionname { get; set; }

        [Display(Name = "Subject Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Subject Name is required")]
        public string subjectname { get; set; }

        [Display(Name = "Quiz 1 mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quiz 2 mark is required")]
        public int quiz1 { get; set; }

        [Display(Name = "Quiz 2 mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quiz 2 mark is required")]
        public int quiz2 { get; set; }

        [Display(Name = "Assignment mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Assignment mark is required")]
        public int assignment1 { get; set; }

        [Display(Name = "Half Yearly Grade")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Half Yearly Grade is required")]
        public int halfyearlygrade { get; set; }

        [Display(Name = "Quiz 3 mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quiz 3 mark is required")]
        public int quiz3 { get; set; }

        [Display(Name = "Quiz 4 mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quiz 4 mark is required")]
        public int quiz4 { get; set; }

        [Display(Name = "Assignment 2 mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Assignment 2 mark is required")]
        public int assignment2 { get; set; }

        [Display(Name = "Final Grade mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Final Grade is required")]
        public int finalexamgrade { get; set; }
    }
}

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Models/Extended/teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mid_SchoolManagementSystem.Models.DataAccess
{
    [MetadataType(typeof(teacherdata))]
    public partial class teacher
    {
        public string teacherconfirmpassword { get; set; }
    }

    public class teacherdata
    {
        public int id { get; set; }

        [Display(Name = "Teacher ID")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Admin ID is required")]
        public string teacherid { get; set; }

        [Display(Name = "Teacher Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Admin Name is required")]
        public string teachername { get; set; }

        [Display(Name = "Teacher Password")]
        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Teacher Password is required")]
        [MinLength(8, ErrorMessage = "Atleast 8 characters required")]
        public string teacherpassword { get; set; }

        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("teacherpassword", ErrorMessage = "Passwords do not match!")]
        public string teacherconfirmpassword { get; set; }

        [Display(Name = "Blood Group")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Blood Group is required")]
        [MaxLength(3, ErrorMessage = "Atmost 3 characters required")]
        public string teacherbloodgroup { get; set; }

        [Display(Name = "Email Adddress")]
        [DataType(DataType.EmailAddress)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email Address is required")]
        public string teacheremail { get; set; }

        [Display(Name = "Subject Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Subject Name is required")]
        public string subjectid { get; set; }

        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone Number is required")]

        
        public int teacherphone { get; set; }
        [Display(Name = "Salary")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Salary is required")]
        public int teachersalary { get; set; }
    }
}

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Controllers/TeacherController.cs
using Mid_SchoolManagementSystem.Models.DataAccess;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mid_SchoolManagementSystem.Controllers
{
    public class TeacherController : Controller
    {
        smsEntities data = new smsEntities();

        //Teacher landing page or INDEX
        [HttpGet]
        public ActionResult TeacherIndex()
        {
            if ((string)Session["user"] != null)
            {
                return View();
            }
            return RedirectToAction("Login", "User");
        }


        //UploadFile get       
        [HttpGet]
        public ActionResult UploadFile()
        {
            if ((string)Session["user"] != null)
            {
                return View();
            }
            return RedirectToAction("Login", "User");
        }



        //Upload File post
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file, uploadnote uploadnote, @class classid, section section, teacher teacher)
        {
            if ((string)Session["user"] != null)
            {
                smsEntities data = new smsEntities();
                try
                {
                    if (file.ContentLength > 0)
                    {

                        string FileName = Path.GetFileName(file.FileName);
                        string path = Path.Combine(Server.MapPath("~/UploadedFiles"), FileName);
                        file.SaveAs(path);

                    }
                    ViewBag.Message = "File Uploaded Successfully!!";
                    return View();
                }
                catch
                {
                    ViewBag.Message = "File upload failed!!";
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }


        ////UploadFile get       
        //[HttpGet]

        //public ActionResult UploadFile()
        //{
        //    using (smsEntities data = new smsEntities())
        //    {

        //        string id = (string)Session["user"];

        //        teacher teacher = data.teacher.Where(x => x.teacherid == id).FirstOrDefault();

        //        var sec = new SelectList(data.section.ToList(), "sectionid", "sectionname");
        //        ViewData["sectionlist"] = sec;

        //        var sub = new SelectList(data.subject.ToList(), "subjectid", "subjectname");
        //        ViewData["sublistlist"] = sub;
        //    }
        //    return View();
        //}
        ////Upload File post
        //[HttpPost]
        //public ActionResult UploadFile(HttpPostedFileBase file, uploadnote uploadnote)
        //{
        //    smsEntities data = new smsEntities();
        //    try
        //    {
        //        if (file.ContentLength > 0)
        //        {
        //            string FileName = Path.GetFileName(file.FileName);
        //            string path = Path.Combine(Server.MapPath("~/UploadedFiles"), FileName);
        //            file.SaveAs(path);


        //            data.uploadnote.Add(uploadnote);
        //            data.SaveChanges();

        //        }
        //        ViewBag.Message = "File Uploaded Successfully!!";
        //        return View();
        //    }
        //    catch
        //    {
        //        ViewBag.Message = "File upload failed!!";
        //        return View();
        //    }
        //}



        //Edit Teacher GET
        [HttpGet]
        public ActionResult EditTeacherProfile()
        {
            if ((string)Session["user"] != null)
            {
                string teacherid = (string)Session["user"];

                teacher t = data.teacher.Where(x => x.teacherid == teacherid).FirstOrDefault();

                t.teacherid = teacherid;
                teacher[] teacher = data.teacher.ToArray();
                ViewData["teacher"] = teacher;

                var fromDatabaseEF = new SelectList(data.@class.ToList(), "classid", "classname");
                var sec = new SelectList(data.section.ToList(), "sectionid", "sectionname");
                var sub = new SelectList(data.subject.ToList(), "subjectid", "subjectname");
                ViewData["classlist"] = fromDatabaseEF;
                ViewData["sectionlist"] = sec;
                ViewData["subjectlist"] = sub;

                return View(t);
            }
            return RedirectToAction("Login", "User");
        }


        //Edit Teacher POST
        [HttpPost]
        public ActionResult EditTeacherProfile(teacher t, int id)
        {
            if ((string)Session["user"] != null)
            {
                teacher teacher = new teacher();


                teacher teachertoupdate = data.teacher.Where(x => x.id == id).FirstOrDefault();
                //Debug.WriteLine(superadmintoupdate);
                //Debug.WriteLine(id);
                //Debug.WriteLine(s.superadminid);
                //Debug.WriteLine(s.superadminname);
                //Debug.WriteLine(s.superadminpassword);
                //Debug.WriteLine(s.superadminconfirmpassword);
                //superadmintoupdate.id = s.id;
                teachertoupdate.teacherid = t.teacherid;
                teachertoupdate.teachername = t.teachername;
                teachertoupdate.teacherphone = t.teacherphone;
                teachertoupdate.teacherbloodgroup = t.teacherbloodgroup;
                teachertoupdate.teacheremail = t.teacheremail;
                teachertoupdate.teacherpassword = Crypto.Hash(t.teacherpassword);
                teachertoupdate.teacherconfirmpassword = Crypto.Hash(t.teacherconfirmpassword);




                try
                {
                    data.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Debug.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Debug.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    throw;
                }

                return RedirectToAction("TeacherIndex");
            }
            return RedirectToAction("Login", "User");

        }
        //CourseNotice GET       
        [HttpGet]

        public ActionResult CreateCourseNotice()
        {
            if ((string)Session["user"] != null)
            {
                string teacherid = (string)Session["user"];
                Debug.WriteLine(teacherid);
                //section[] sec = data.section.ToArray();

                //TempData["sectionlist"] = sec;
              //subject[] sub = data.subject.ToArray();

                //TempData["subjectlist"] = sub;
                //var id = (string)Session["user"];
                assignedcourse[] noticeinfo = data.assignedcourse.Where(x => x.teacherid == teacherid).ToArray();
                TempData["teacherinfo"] = noticeinfo;

                return View();
            }
            
            return RedirectToAction("Login", "User");
        }

        [HttpPost]

        public ActionResult CreateCourseNotice(coursenotice notice)
        {
            if ((string)Session["user"] != null)
            {
                data.coursenotice.Add(notice);
                data.SaveChanges();
                return RedirectToAction("TeacherIndex");
            }
            return RedirectToAction("Login", "User");
        }

        //Grade Upload Index

        public ActionResult Grades()
        {
            if ((string)Session["user"] != null)
            {
                
                return View(data.grade);
            }
            return RedirectToAction("Login", "User");
        }

        //Uploda Grades Get

        [HttpGet]

        public ActionResult UploadGrade()
        {
            if ((string)Session["user"] != null)
            {
                string teacherid = (string)Session["user"];
                Debug.WriteLine(teacherid);
                assignedcourse[] noticeinfo = data.assignedcourse.Where(x => x.teacherid == teacherid).ToArray();
                TempData["teacherinfo"] = noticeinfo;
                //var cls = new SelectList(data.@class.ToList(), "classname", "classname");
                //var stu = new SelectList(data.student.ToList(), "studentname", "studentname");
                //var sec = new SelectList(data.section.ToList(), "sectionname", "sectionname");
                //var sub = new SelectList(data.subject.ToList(), "subjectname", "subjectname");
                //ViewData["classlist"] = cls;
                //ViewData["studentlist"] = stu;
                //ViewData["sectionlist"] = sec;
                //ViewData["subjectlist"] = sub;


                return View();
            }
            return RedirectToAction("Login", "User");
        }

        //Upload Grade Post
        [HttpPost]
        public ActionResult UploadGrade(grade grade)
        {
            if ((string)Session["user"] != null)
            {
                RedirectToAction("ViewGrade","Student");
                Debug.WriteLine(grade.quiz2);
                data.grade.Add(grade);
                  Debug.WriteLine(grade.quiz1);
                data.SaveChanges();

            }
            return View("Grades");
        }
        //Edit Grades Get

        [HttpGet]
        public ActionResult EditGrades(int id)
        {
            if ((string)Session["user"] != null)
            {

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Views/Teacher/CreateCourseNotice.cshtml
@model Mid_SchoolManagementSystem.Models.DataAccess.coursenotice

@{
    Layout = null;
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateCourseNotice</title>
</head>
<body>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#classid").change(function () {
                $.get("/Data/GetSectionAssigned", { classid/*variable*/: $("#classid"/*dropdownid*/).val() }, function (data) {
                    $("#sectionid"/*2nd dropdown needs to be changed*/).empty();
                    $.each(data, function (index, row) {
                        $("#sectionid").append("<option value='" + row.sectionid /*backendid*/ + "'>" + row.sectionid /*print*/ + "</option>")
                    });
                });
                $.get("/Data/GetSubjectAssigned", { classid: $("#classid").val() }, function (data) {
                    $("#subjectid").empty();
                    $.each(data, function (index, row) {
                        $("#subjectid").append("<option value='" + row.subjectid + "'>" + row.subjectid + "</option>")
                    });
                });
            })
        });
    </script>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CreateCourseNotice</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.noticeid)

            <div class="form-group">
                @Html.LabelFor(model => model.noticesubject, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.noticesubject, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noticesubject, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" id="editor-field">
                @Html.LabelFor(model => model.noticedescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.noticedescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noticedescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.sectionid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("sectionid", new SelectList(" "), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.sectionid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.subjectid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("subjectid", new SelectList(" "), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.subjectid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.classid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    <select id="classid" name="classid">
                        <option>Select One</option>
                        @foreach (var item in (Mid_SchoolManagementSystem.Models.DataAccess.assignedcourse[])TempData["teacherinfo"])
                        {
                            <option value="@item.classid">
                                @item.classid
                            </option>
                        }

                    </select>
                    @Html.ValidationMessageFor(model => model.classid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to Home", "TeacherIndex")
    </div>
</body>
</html>

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Views/Teacher/EditGrades.cshtml
@model Mid_SchoolManagementSystem.Models.DataAccess.grade

@{
    ViewBag.Title = "EditGrades";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>EditGrades</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>grade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.gradeid)

        <div class="form-group">
            @Html.LabelFor(model => model.classname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.classname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.classname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sectionname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sectionname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.sectionname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subjectname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subjectname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.subjectname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.studentname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.studentname, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.studentname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assignment1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assignment1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assignment1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.halfyearlygrade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.halfyearlygrade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.halfyearlygrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quiz4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quiz4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quiz4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.assignment2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assignment2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assignment2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.finalexamgrade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.finalexamgrade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.finalexamgrade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Grades")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Mid_SchoolManagementSystem/Mid_SchoolManagementSystem/Views/Teacher/UploadFile.cshtml
@model Mid_SchoolManagementSystem.Models.DataAccess.uploadnote

@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>UploadFile</h2>


@using (Html.BeginForm("UploadFile", "Teacher", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    {

        <div class="form-group">
            @Html.TextBox("file", "", new { type = "file" }) <br />

            <input type="submit" value="Upload" />

            @ViewBag.Message

        </div>

        <div>
            @Html.ActionLink("Clear", "UploadFile")
        </div>
    }
}

@*<div class="form-group">
        @Html.LabelFor(model => model.directory, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.directory, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.directory, "", new { @class = "text-danger" })
        </div>
    </div>*@

@*<div class="form-group">
        @Html.LabelFor(model => model.filename, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.filename, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.filename, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.datetime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.datetime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.datetime, "", new { @class = "text-danger" })
        </div>
    </div>*@

@*<div class="form-group">
        @Html.LabelFor(model => model.sectionid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("sectionid", (IEnumerable<SelectListItem>)ViewData["sectionlist"])
            @Html.ValidationMessageFor(model => model.sectionid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.subjectid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("subjectid", (IEnumerable<SelectListItem>)ViewData["subjectlist"])
            @Html.ValidationMessageFor(model => model.subjectid, "", new { @class = "text-danger" })
        </div>
    </div>*@

@*<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>*@



<div>
    @Html.ActionLink("Back to Home Page", "TeacherIndex")
</div>